name: c_course
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning for the app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #share_plus: ^6.0.0 # Updated to a null-safety compatible version
  url_launcher: ^6.0.10 # Updated to a null-safety compatible version
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/icons/starting_icon/
    - lib/assets/icons/apk_icon/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/apk_icon/apk_icon.png"